SELECT USERS.*, POST.*, LIKES.*, COMMENTS.*, FOLLOWERS.*
FROM USERS
LEFT JOIN POST ON USERS.user_id = POST.user_id
LEFT JOIN LIKES ON POST.post_id = LIKES.post_id
LEFT JOIN COMMENTS ON POST.post_id = COMMENTS.post_id
LEFT JOIN FOLLOWERS ON USERS.user_id = FOLLOWERS.user_id;
